# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "lishaduck"
    groups:
      github:
        patterns:
          - "actions/*"

  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "lishaduck"
    groups:
       riverpod:
          patterns:
            - "*riverpod*"
       auto_route:
          patterns:
            - "auto_route*"
       freezed:
          patterns:
            - "freezed*"
            - "json_*"
       widgetbook:
          patterns:
            - "widgetbook*"
       build:
          patterns:
            - "build*"
      envied:
          patterns:
            - "envied*"
